global:
  scrape_interval: 5s
  scrape_timeout: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: producer
    static_configs:
      - targets:
          - producer:8080
  - job_name: consumer
    static_configs:
      - targets:
          - consumer:8080
  - job_name: redis
    static_configs:
      - targets:
          - redis-exporter:9121
